-- Generated by HyprMod

-- Settings
hl.config({
    general = {
        allow_tearing = true,
        gaps_in = 1,
        gaps_out = 6,
        snap = {
            enabled = false,
        },
    },
    gestures = {
        workspace_swipe_forever = true,
    },
    misc = {
        mouse_move_enables_dpms = true,
        vrr = 2,
    },
})
