-- ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
-- ◈ AUTOSTART (OPTIMIZED & DEBLOATED)
-- ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
hl.on("hyprland.start", function()
    hl.exec_cmd("dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP QT_QPA_PLATFORMTHEME")
    hl.exec_cmd("systemctl --user import-environment WAYLAND_DISPLAY XDG_CURRENT_DESKTOP QT_QPA_PLATFORMTHEME")
    hl.exec_cmd("systemctl --user start hyprpolkitagent")
    hl.exec_cmd("awww-daemon")
    hl.exec_cmd("hypridle")
    hl.exec_cmd("bash -c 'mkdir -p ~/.cache/quickshell/run/logs && quickshell -p ~/.config/hypr/scripts/quickshell/Shell.qml > ~/.cache/quickshell/run/logs/quickshell.log 2>&1'")
    hl.exec_cmd("~/.config/hypr/scripts/init.sh")
    hl.exec_cmd("~/.config/hypr/scripts/settings_watcher.sh &")
    hl.exec_cmd("playerctld")
    hl.exec_cmd("wl-paste --type text --watch cliphist store")
    hl.exec_cmd("wl-paste --type image --watch cliphist store")
    hl.exec_cmd("~/.config/hypr/scripts/hdmi_watcher.sh &")
    hl.exec_cmd("bash ~/.config/hypr/scripts/turbo_inhibitor.sh sync &")
    hl.exec_cmd("bash -c 'sleep 1 && ~/.config/hypr/scripts/qs_manager.sh toggle guide'")
end)
