-- ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

-- ◈ ENVIRONMENT VARIABLES (AUTOGENERATED)

-- ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
hl.env("ELECTRON_OZONE_PLATFORM_HINT", "auto")
hl.env("OZONE_PLATFORM", "wayland")
hl.env("XDG_PICTURES_DIR", os.getenv("HOME") .. "/Pictures")
hl.env("XDG_VIDEOS_DIR", os.getenv("HOME") .. "/Videos")
hl.env("WALLPAPER_DIR", os.getenv("HOME") .. "/Pictures/Wallpapers")
hl.env("SCRIPT_DIR", os.getenv("HOME") .. "/.config/hypr/scripts")
hl.env("QT_QPA_PLATFORMTHEME", "qt6ct")
hl.env("QT_WAYLAND_DISABLE_WINDOWDECORATION", "1")

-- Hardware Injections
local handle = io.popen("lspci -nn 2>/dev/null | grep -iE 'vga|3d|display'")
if handle then
    local gpu = handle:read("*a") or ""
    handle:close()
    if gpu:lower():find("nvidia") then
        hl.env("LIBVA_DRIVER_NAME", "nvidia")
        hl.env("__GLX_VENDOR_LIBRARY_NAME", "nvidia")
        hl.env("NVD_BACKEND", "direct")
    elseif gpu:lower():find("amd") or gpu:lower():find("advanced micro devices") then
        hl.env("LIBVA_DRIVER_NAME", "radeonsi")
        hl.env("VDPAU_DRIVER", "radeonsi")
    elseif gpu:lower():find("intel") then
        hl.env("LIBVA_DRIVER_NAME", "iHD")
        hl.env("VDPAU_DRIVER", "va_gl")
    end
end
