-- ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

-- ◈ ENVIRONMENT VARIABLES (AUTOGENERATED)

-- ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
hl.env("NIXOS_OZONE_WL", "1")
hl.env("ELECTRON_OZONE_PLATFORM_HINT", "auto")
hl.env("OZONE_PLATFORM", "wayland")
hl.env("XDG_PICTURES_DIR", "/home/anesu")
hl.env("XDG_VIDEOS_DIR", "/home/anesu")
hl.env("WALLPAPER_DIR", "/home/anesu/Pictures/Wallpapers")
hl.env("SCRIPT_DIR", "/home/anesu/.config/hypr/scripts")
hl.env("QT_QPA_PLATFORMTHEME", "qt6ct")

-- Hardware Injections
