-- ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

-- ◈ SETTINGS (AUTOGENERATED FROM SETTINGS.JSON)

-- ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
hl.config({
    general = {
        border_size = 2,
        gaps_in = 4,
        gaps_out = 4,
        float_gaps = 6,
        resize_on_border = true,
        extend_border_grab_area = 30,
        col = {
            active_border = var_active_border,
            inactive_border = var_inactive_border,
        },
    },
    decoration = {
        rounding = 8,
        active_opacity = 1.0,
        inactive_opacity = 0.94,
        dim_inactive = true,
        dim_strength = 0.08,
        blur = {
            enabled = true,
            size = 8,
            passes = 2,
            new_optimizations = true,
            xray = true,
            ignore_opacity = true,
        },
        shadow = {
            enabled = false,
        },
    },
    input = {
        kb_layout = "us",
        kb_options = "grp:alt_shift_toggle",
        touchpad = {
            natural_scroll = true,
        },
    },
    cursor = {
        no_warps = true,
    },
    misc = {
        font_family = "JetBrains Mono",
        disable_hyprland_logo = true,
        disable_splash_rendering = true,
        force_default_wallpaper = 0,
        vrr = 0,
    },
    render = {
        direct_scanout = 1,
    },
    ecosystem = {
        no_update_news = true,
        no_donation_nag = true,
    },
    animations = {
        enabled = true,
    },
})

hl.curve("myBezier", { type = "bezier", points = { {0.05, 0.9}, {0.1, 1.05} } })
hl.curve("smoothOut", { type = "bezier", points = { {0.16, 1}, {0.3, 1} } })
hl.curve("smoothIn", { type = "bezier", points = { {0.25, 1}, {0.5, 1} } })

hl.animation({
    leaf = "windows",
    enabled = true,
    speed = 4,
    bezier = "smoothOut",
    style = "popin 85%",
})
hl.animation({
    leaf = "windowsOut",
    enabled = true,
    speed = 3,
    bezier = "smoothIn",
    style = "popin 85%",
})
hl.animation({
    leaf = "windowsMove",
    enabled = true,
    speed = 4,
    bezier = "smoothOut",
})
hl.animation({
    leaf = "layers",
    enabled = true,
    speed = 4,
    bezier = "smoothOut",
    style = "fade",
})
hl.animation({
    leaf = "layersIn",
    enabled = true,
    speed = 3,
    bezier = "smoothOut",
    style = "fade",
})
hl.animation({
    leaf = "layersOut",
    enabled = true,
    speed = 3,
    bezier = "smoothIn",
    style = "fade",
})
hl.animation({
    leaf = "fade",
    enabled = true,
    speed = 4,
    bezier = "smoothOut",
})
hl.animation({
    leaf = "workspaces",
    enabled = true,
    speed = 5,
    bezier = "smoothOut",
    style = "slide",
})
hl.animation({
    leaf = "specialWorkspaceIn",
    enabled = true,
    speed = 4,
    bezier = "smoothOut",
    style = "fade",
})
hl.animation({
    leaf = "specialWorkspaceOut",
    enabled = true,
    speed = 3,
    bezier = "smoothIn",
    style = "fade",
})
